name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      EMULATOR_PORT: 8085
      FIRESTORE_EMULATOR_HOST: localhost:8085
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: test-project

      - name: Start Firestore Emulator
        run: |
          echo "Starting Firestore emulator on port $EMULATOR_PORT..."
          gcloud components install cloud-firestore-emulator
          gcloud beta emulators firestore start --host-port=localhost:$EMULATOR_PORT --quiet &
          # Wait for emulator port to be open
          echo "Waiting for Firestore emulator to accept connections..."
          until nc -z localhost $EMULATOR_PORT; do sleep 1; done
          # Wait a few more seconds to ensure emulator is fully ready
          sleep 5
          echo "Firestore emulator is ready."
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8085

      - name: Build and run tests with test profile
        run: ./gradlew clean test -Dspring.profiles.active=test --info
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8085
